### PR TITLE
kexec is a path

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

**Review by Lassulus — APPROVED** [review]

**Comment by Lassulus** [comment]
@mergify queue

**Comment by phaer** [comment]
Is that true?

--kexec sets kexec_url, which is only a path if neither curl nor kexec are available?
if it was, renaming kexec_url to kexec_path would also good to include here?

https://github.com/numtide/nixos-anywhere/blob/e516d378d6a7baea37474347aff94062d5678761/src/nixos-anywhere.sh#L337

**Comment by domenkozar** [comment]
Would `(exec|path)` work?

**Comment by phaer** [comment]
Yes, I do think so. That wouldn't hide the fact that it can be, and the default is, an URL.

**Pull request merged**
